# Generated by Django 3.2 on 2021-04-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='recipe',
            new_name='diary_body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='food_title',
            new_name='diary_title',
        ),
    ]
